"use client";
import {upload as uploadBlob} from "@vercel/blob/client";
import {useEffect,useState,useRef,useCallback} from "react";
import {Network,LayoutGrid,CheckCheck,CalendarDays,NotebookPen,FolderOpen,Wallet,Link2,Plus,Minus,Maximize,Orbit,SlidersHorizontal,ChevronRight,Send,Sparkles,LoaderCircle,Trash2,Check,ArrowUpRight,Upload,RefreshCw,Pencil,X,LockKeyhole,Home,Bell,ChevronDown,LogIn} from "lucide-react";
import NetworkGraph from "./network-graph";
import WorkspaceSearch from "./workspace-search";
import PrivateArea from "./private-area";
import AccountDialog,{type AccountContext} from "./account-dialog";
import {isDeletionConfirmation,isDeletionCancellation,type DeletionTarget} from "@/lib/chat-actions";
import {modules,Entry,Kind} from "@/lib/dashhan";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogAction,AlertDialogCancel,AlertDialogFooter} from "@/components/ui/alert-dialog";
import {Checkbox} from "@/components/ui/checkbox";
import {Switch} from "@/components/ui/switch";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";
import {Toaster,toast} from "sonner";
const icons=[LayoutGrid,CheckCheck,CalendarDays,NotebookPen,FolderOpen,Wallet,Link2];
type Chat={role:"user"|"assistant";content:string};
type Draft={id?:string;kind:Kind;title:string;body:string;date:string;url:string;amount:number;priority:string;status?:number};
const fresh=(kind:Kind):Draft=>({kind,title:"",body:"",date:"",url:"",amount:0,priority:"normal"});
async function api(path:string,method="GET",body?:unknown){const r=await fetch(path,{method,headers:body instanceof FormData?undefined:body?{"Content-Type":"application/json"}:undefined,body:body instanceof FormData?body:body?JSON.stringify(body):undefined});const d=await r.json() as {error?:string;entries:Entry[];reply:string;focus:Kind|"core";proposal:Draft|null;model:string;deletion:DeletionTarget|null;deletedId?:string;alreadyDeleted?:boolean};if(!r.ok)throw new Error(d.error||"İşlem tamamlanamadı.");return d;}
export default function Dashboard({account}:{account:AccountContext}){
 const [accountOpen,setAccountOpen]=useState(false),[privateOpen,setPrivateOpen]=useState(false),[deletion,setDeletion]=useState<DeletionTarget|null>(null);
 const chatWorking=useRef(false);
 const [entries,setEntries]=useState<Entry[]>([]),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(""),[selected,setSelected]=useState<Kind|"core">("core"),[zoom,setZoom]=useState(1),[reset,setReset]=useState(0),[motion,setMotion]=useState(true),[settings,setSettings]=useState(false),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[chat,setChat]=useState<Chat[]>([]),[aiError,setAiError]=useState(""),[proposal,setProposal]=useState<Draft|null>(null),[draft,setDraft]=useState<Draft|null>(null),[saving,setSaving]=useState(false),[remove,setRemove]=useState<Entry|null>(null),[model,setModel]=useState("Gemini"),[now,setNow]=useState<Date|null>(null);
 const fileInput=useRef<HTMLInputElement>(null),chatEnd=useRef<HTMLDivElement>(null),input=useRef<HTMLInputElement>(null);
 const refresh=useCallback(async()=>{setLoading(true);try{const d=await api("/api/entries");setEntries(d.entries);setLoadError("");}catch(e){setLoadError((e as Error).message);}finally{setLoading(false);}},[]);
 useEffect(()=>{void refresh();setNow(new Date());const t=setInterval(()=>setNow(new Date()),30000);return()=>clearInterval(t);},[refresh]);
 useEffect(()=>{chatEnd.current?.scrollIntoView({behavior:"smooth",block:"nearest"});},[chat,busy]);
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>|void}}).modelContext;if(!context)return;const life=new AbortController();Promise.resolve(context.registerTool({name:"open_dashhan_module",title:"DashHAN bölümünü aç",description:"Projeler, görevler, ajanda, notlar, dosyalar, finans veya hızlı linkler panelini açar.",inputSchema:{type:"object",properties:{module:{type:"string",enum:["core",...modules.map(m=>m.id)]}},required:["module"],additionalProperties:false},annotations:{readOnlyHint:true},execute:(v:unknown)=>{const id=(v as {module?:string})?.module;if(id!=="core"&&!modules.some(m=>m.id===id))throw new Error("Geçersiz bölüm");setSelected(id as Kind|"core");return {opened:id};}},{signal:life.signal})).catch(()=>{});return()=>life.abort();},[]);
 const open=entries.filter(e=>e.kind==="tasks"&&!e.status),done=entries.filter(e=>e.kind==="tasks"&&e.status),high=open.filter(e=>e.priority==="high");
 const module=modules.find(m=>m.id===selected),rows=entries.filter(e=>e.kind===selected).sort((a,b)=>selected==="calendar"?a.date.localeCompare(b.date):0);
 const taskPreview=[...open.filter(e=>e.priority==="high"),...open.filter(e=>e.priority!=="high")].slice(0,3);
 async function save(value:Draft){setSaving(true);try{await api("/api/entries",value.id?"PATCH":"POST",{...value,date:value.date?new Date(value.date).toISOString():""});setDraft(null);setProposal(null);await refresh();toast.success("Kayıt kaydedildi.");}catch(e){toast.error((e as Error).message);}finally{setSaving(false);}}
 async function toggle(e:Entry){try{await api("/api/entries","PATCH",{id:e.id,status:e.status?0:1});await refresh();}catch(e){toast.error((e as Error).message);}}
 async function ask(text:string){
  if(busy||chatWorking.current||!text.trim())return;
  chatWorking.current=true;setBusy(true);setAiError("");setProposal(null);setChat(c=>[...c,{role:"user",content:text}]);setMessage("");
  try{
   if(deletion&&isDeletionCancellation(text)){
    setDeletion(null);setChat(c=>[...c,{role:"assistant",content:"Silme işlemini iptal ettim."}]);return;
   }
   if(deletion&&isDeletionConfirmation(text)){
    const result=await api("/api/entries","DELETE",{id:deletion.id});
    if(result.deletedId!==deletion.id)throw new Error("Silme işlemi doğrulanamadı. Yeniden dene.");
    setEntries(current=>current.filter(entry=>entry.id!==deletion.id));
    setDraft(current=>current?.id===deletion.id?null:current);setRemove(current=>current?.id===deletion.id?null:current);
    setDeletion(null);await refresh();
    setChat(c=>[...c,{role:"assistant",content:result.alreadyDeleted?`“${deletion.title}” kaydı artık bulunmuyor.`:`“${deletion.title}” kaydını sildim.`}]);return;
   }
   setDeletion(null);
   const d=await api("/api/ai","POST",{message:text,history:chat.slice(-14)});
   setChat(c=>[...c,{role:"assistant",content:d.reply}]);if(d.focus)setSelected(d.focus);
   setProposal(d.proposal);setDeletion(d.deletion??null);setModel(d.model);
  }catch(e){setAiError((e as Error).message);setMessage(text);setChat(c=>c.slice(0,-1));}
  finally{chatWorking.current=false;setBusy(false);}
 }

 async function upload(f:File){if(!f.size||f.size>10*1024*1024){toast.error("En fazla 10 MB büyüklüğünde bir dosya seç.");return;}setSaving(true);try{const user=account.user;if(!user)throw new Error("Önce giriş yap.");const path=`files/${account.userId}/${crypto.randomUUID()}`;const blob=await uploadBlob(path,f,{access:"private",handleUploadUrl:"/api/files/upload",multipart:f.size>4*1024*1024});await api("/api/files","POST",{pathname:blob.pathname,title:f.name.slice(0,200)});await refresh();toast.success("Dosya yüklendi.");}catch(e){toast.error((e as Error).message);}finally{setSaving(false);if(fileInput.current)fileInput.current.value="";}}
 const newEntry=()=>selected==="files"?fileInput.current?.click():setDraft(fresh(selected==="core"?"tasks":selected));
 return <main className="dashhan"><Toaster theme="dark" position="top-center"/><header className="topbar reference-topbar">
  <svg className="topbar-orbit" viewBox="0 0 400 200" fill="none" aria-hidden="true"><circle cx="200" cy="100" r="94"/><ellipse cx="200" cy="100" rx="48" ry="94"/><ellipse cx="200" cy="100" rx="94" ry="34"/><path d="M106 100h188M200 6v188"/></svg>
  <button className="brand" onClick={()=>setSelected("core")} aria-label="DashHAN ana merkez"><span className="brand-symbol brand-logo" aria-hidden="true"><img src="/dashhan-logo.png" alt="" width={52} height={52} decoding="async"/></span><span className="brand-wordmark">Dash<span className="gold">HAN</span><small>KİŞİSEL KONTROL MERKEZİ</small></span></button>
  <div className="top-context"><div className="top-breadcrumb"><button className="top-home" onClick={()=>setSelected("core")} aria-label="Çalışma alanı ana sayfası"><Home size={17}/></button><button onClick={()=>setSelected("core")}>Çalışma alanı</button><ChevronRight size={13}/><span>{module?.name||"AI Merkez"}</span></div><span className="top-context-caption">{selected==="core"?"Tüm bağlantıların tek merkezde":module?.label.toLocaleLowerCase("tr-TR")}</span></div>
  <WorkspaceSearch entries={entries} loading={loading} onSelect={entry=>{setSelected(entry.kind);if(entry.kind==="files")window.location.assign(`/api/files?id=${encodeURIComponent(entry.id)}`);else setDraft({...entry});}}/>
  <div className="top-actions">
   <div className="top-date"><CalendarDays size={18} strokeWidth={1.5}/><div><span>{now?new Intl.DateTimeFormat("tr-TR",{day:"numeric",month:"short",year:"numeric",timeZone:"Europe/Istanbul"}).format(now):"—"}</span><strong>{now?new Intl.DateTimeFormat("tr-TR",{hour:"2-digit",minute:"2-digit",timeZone:"Europe/Istanbul"}).format(now):"—"}<small>IST</small></strong></div></div>
   <button className="icon-button top-notifications" onClick={()=>setSelected("tasks")} aria-label={`Görevleri aç${high.length?`, ${high.length} öncelikli görev`:""}`}><Bell size={18} strokeWidth={1.5}/>{high.length>0&&<i aria-hidden="true"/>}</button>
   <button className="privacy-badge" onClick={()=>setPrivateOpen(true)} aria-label="Şifreli özel alanı aç" aria-haspopup="dialog" aria-expanded={privateOpen}><LockKeyhole size={14}/><span>Özel alan</span></button>
   <button className="new-button" onClick={newEntry} aria-label="Yeni kayıt"><Plus size={17}/><span>Yeni kayıt</span></button>
   <button className="icon-button settings-button" onClick={()=>setSettings(true)} aria-label="Görünüm ayarları"><SlidersHorizontal size={18}/></button>
   <button className="top-profile" onClick={()=>setAccountOpen(true)} aria-label="Giriş yap veya kayıt ol" aria-haspopup="dialog" aria-expanded={accountOpen}><span className="avatar"><LogIn size={19}/></span><ChevronDown size={13}/></button>
  </div>
 </header>
 <nav className="rail" aria-label="Bölümler"><button title="AI Merkez" aria-label="AI Merkez" aria-pressed={selected==="core"} className={selected==="core"?"active":""} onClick={()=>setSelected("core")}><Network size={21}/></button><div className="rail-line"/>{modules.map((m,i)=>{const Icon=icons[i];return <button key={m.id} title={m.name} aria-label={m.name} aria-pressed={selected===m.id} className={selected===m.id?"active":""} onClick={()=>setSelected(m.id)} style={{"--node-color":m.color} as React.CSSProperties}><Icon size={20}/></button>;})}<span className="rail-bottom"><LockKeyhole size={18}/></span></nav>
 <section className="map-region"><NetworkGraph entries={entries} focus={selected} onSelect={setSelected} zoom={zoom} onZoom={setZoom} motion={motion} reset={reset}/><div className="map-caption"><span className="eyebrow">BAĞLANTI HARİTASI</span><h1>Her şey birbiriyle bağlı.</h1><p>Fikirlerin, planların, bir sonraki adımın.</p></div><div className="map-tools"><button onClick={()=>setZoom(z=>Math.min(1.8,z+.15))} aria-label="Yakınlaştır"><Plus size={17}/></button><span>{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(z=>Math.max(.55,z-.15))} aria-label="Uzaklaştır"><Minus size={17}/></button><i/><button onClick={()=>{setZoom(1);setReset(r=>r+1);}} aria-label="Görünümü sıfırla"><Maximize size={17}/></button><button className={motion?"lit":""} onClick={()=>setMotion(m=>!m)} aria-label="Animasyonu aç veya durdur"><Orbit size={18}/></button></div><div className="map-hint">Tekerlek: yakınlaştır / uzaklaştır<span>Sürükle: taşı · SHIFT + sürükle: döndür</span></div></section>
 <aside className="today-panel"><div className="eyebrow">BUGÜN</div><div className="date-number">{now?new Intl.DateTimeFormat("tr-TR",{day:"2-digit",timeZone:"Europe/Istanbul"}).format(now):"—"}<span>{now?new Intl.DateTimeFormat("tr-TR",{month:"long",year:"numeric",timeZone:"Europe/Istanbul"}).format(now):""}</span></div><p className="weekday">{now?new Intl.DateTimeFormat("tr-TR",{weekday:"long",timeZone:"Europe/Istanbul"}).format(now):""}</p><div className="today-divider"/><div className="progress-heading"><span>Günün ritmi</span><span>{done.length+open.length?Math.round(done.length/(done.length+open.length)*100):0}%</span></div><div className="progress-track"><i style={{width:`${done.length+open.length?done.length/(done.length+open.length)*100:0}%`}}/></div><p className="subtle">{done.length} tamamlandı · {open.length} açık görev</p><div className="up-next"><span className="eyebrow">SIRADAKİ</span>{entries.filter(e=>e.kind==="calendar"&&e.date&&new Date(e.date)>=new Date()).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,1).map(e=><button key={e.id} onClick={()=>setSelected("calendar")}><span>{e.title}</span><small>{new Date(e.date).toLocaleString("tr-TR",{timeZone:"Europe/Istanbul"})}</small></button>)}{!entries.some(e=>e.kind==="calendar"&&e.date&&new Date(e.date)>=new Date())&&<button onClick={()=>setDraft(fresh("calendar"))}><span>Ajandan sana ait.</span><small>İlk planını ekle <Plus size={12}/></small></button>}</div></aside>
 <aside className="focus-panel"><div className="panel-top"><span className="eyebrow">{module?.label||"ODAĞIN"}</span><span className="panel-index">{module?String(modules.indexOf(module)+1).padStart(2,"0"):"00"}</span></div><h2>{module?.name||"Bugünün öncelikleri"}</h2><p className="panel-subtitle">{module?`${rows.length} kayıt · senin alanın`:high.length?`${high.length} görev önceliğini bekliyor.`:"Küçük adımlar, büyük ilerleme."}</p>
 {loadError?<div className="error-box"><p>{loadError}</p><button onClick={()=>void refresh()}><RefreshCw size={14}/> Yeniden dene</button></div>:loading?<div className="panel-loading"><LoaderCircle className="spin" size={20}/>Kayıtların yükleniyor</div>:selected==="core"?<><div className="entry-list">{taskPreview.map(e=><div className="task-row" key={e.id}><Checkbox checked={!!e.status} onCheckedChange={()=>void toggle(e)} aria-label={`${e.title} tamamlandı`}/><button className="entry-text" onClick={()=>setDraft({...e})}><strong>{e.title}</strong><small>{e.priority==="high"?"Yüksek öncelik":"Planında"}</small></button></div>)}{taskPreview.length===0&&<div className="empty-state"><CheckCheck size={25}/><h3>Temiz bir başlangıç.</h3><p>İlk görevini ekle, birlikte planlayalım.</p><button onClick={()=>setDraft(fresh("tasks"))}><Plus size={15}/>Görev ekle</button></div>}</div><button className="text-button" onClick={()=>setSelected("tasks")}>Tüm görevler <ChevronRight size={14}/></button><div className="insight-box"><Sparkles size={18}/><p>Bir düşünceyi plana dönüştür.<span>“Bu haftamı planla” diye başla.</span></p></div></>:<><div className="entry-list scroll">{rows.map(e=><div className={`entry-row ${e.status?"completed":""}`} key={e.id}>{(e.kind==="tasks"||e.kind==="projects")&&<Checkbox checked={!!e.status} onCheckedChange={()=>void toggle(e)} aria-label={`${e.title} tamamlandı`}/>}<button className="entry-text" onClick={()=>e.kind==="files"?window.location.assign(`/api/files?id=${e.id}`):setDraft({...e})}><strong>{e.title}</strong><small>{e.kind==="finance"?new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY"}).format(e.amount):e.kind==="files"?`${(e.amount/1024).toFixed(1)} KB`:e.date?new Date(e.date).toLocaleString("tr-TR",{timeZone:"Europe/Istanbul"}):e.body.slice(0,70)||"Düzenlemek için seç"}</small></button>{e.url&&<a href={e.url} target="_blank" rel="noopener noreferrer" aria-label={`${e.title} bağlantısını aç`}><ArrowUpRight size={16}/></a>}<button className="delete-button" aria-label={`${e.title} sil`} onClick={()=>setRemove(e)}><Trash2 size={14}/></button></div>)}{rows.length===0&&<div className="empty-state"><Plus size={24}/><h3>Burada sana yer var.</h3><p>{selected==="files"?"Dosyalarını yükle. En fazla 10 MB.":"İlk kaydını ekleyerek başla."}</p></div>}</div>{selected==="finance"&&<div className="balance"><span>Net toplam</span><strong>{new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY"}).format(rows.reduce((s,e)=>s+e.amount,0))}</strong></div>}<button className="add-entry" onClick={newEntry} disabled={saving}>{selected==="files"?<Upload size={16}/>:<Plus size={16}/>} {selected==="files"?"Dosya yükle":"Yeni kayıt ekle"}</button></>}
 <div className="panel-footer"><span className="live-dot"/>{loading?"Yükleniyor":loadError?"Bağlantı bekleniyor":"Kayıtların güncel"}<span>{entries.length} kayıt</span></div></aside>
 <section className={`command-deck ${chat.length||busy||aiError?"expanded":""}`} aria-label="Gemini asistan"><div className="deck-header"><span><Sparkles size={16}/> DashHAN Asistan</span><span className="gemini-badge">{model.startsWith("gemini-")?"Gemini bağlı":"Gemini"}</span></div>{(chat.length>0||busy||aiError)&&<div className="chat-log" aria-live="polite">{chat.map((c,i)=><div key={i} className={`chat-message ${c.role}`}><small>{c.role==="user"?"SEN":"DASHHAN"}</small><p>{c.content}</p></div>)}{busy&&<div className="thinking"><LoaderCircle size={16} className="spin"/>{deletion?"Silme işlemini doğruluyorum…":"Bağlantıları düşünüyorum…"}</div>}{aiError&&<div className="error-box">{aiError}</div>}{proposal&&<div className="proposal"><span>KAYIT TASLAĞI</span><strong>{proposal.title}</strong><button disabled={saving} onClick={()=>setDraft(proposal)}><Pencil size={14}/>İncele ve kaydet</button><button onClick={()=>setProposal(null)}>Vazgeç</button></div>}{deletion&&<div className="proposal deletion-proposal"><span>SİLME ONAYI</span><strong>{deletion.title}</strong><button disabled={busy} onClick={()=>void ask("Onayla")}><Trash2 size={14}/>Silme işlemini onayla</button><button disabled={busy} onClick={()=>void ask("Vazgeç")}>Vazgeç</button></div>}<div ref={chatEnd}/></div>}<form className="command-form" onSubmit={e=>{e.preventDefault();void ask(message);}}><span className="command-star">✧</span><input ref={input} value={message} onChange={e=>setMessage(e.target.value)} maxLength={4000} placeholder="DashHAN'a bir şey sor…" aria-label="Gemini mesajı" disabled={busy}/><button type="submit" disabled={busy||!message.trim()} aria-label="Mesajı gönder">{busy?<LoaderCircle size={18} className="spin"/>:<Send size={18}/>}</button></form><div className="quick-prompts">{["Bugün neye odaklanmalıyım?","Projelerimi özetle","Haftamı planla"].map(t=><button key={t} disabled={busy} onClick={()=>void ask(t)}>{t}</button>)}</div><div className="deck-stats"><span><i/>{open.length} açık görev</span><span>{entries.filter(e=>e.kind==="projects"&&!e.status).length} aktif proje</span><span>{entries.filter(e=>e.kind==="notes").length} not</span><span className="private-label"><LockKeyhole size={11}/>Sana özel</span></div></section>
 <footer className="workspace-footer"><span>DASHHAN / CONNECTED WORKSPACE</span><span>{now?new Intl.DateTimeFormat("tr-TR",{hour:"2-digit",minute:"2-digit",timeZone:"Europe/Istanbul"}).format(now):""} IST</span></footer>
 <PrivateArea open={privateOpen} onOpenChange={setPrivateOpen} signInPath={account.signInPath}/>
 <AccountDialog open={accountOpen} onOpenChange={setAccountOpen} account={account}/>
 <input hidden type="file" ref={fileInput} onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);}}/>
 <Dialog open={!!draft} onOpenChange={o=>{if(!o&&!saving)setDraft(null);}}><DialogContent className="record-dialog"><DialogHeader><DialogTitle>{draft?.id?"Kaydı düzenle":"Yeni kayıt"}</DialogTitle><DialogDescription>{modules.find(m=>m.id===draft?.kind)?.name} alanına kaydet.</DialogDescription></DialogHeader>{draft&&<form onSubmit={e=>{e.preventDefault();void save(draft);}} className="record-form"><label>Bölüm<Select value={draft.kind} onValueChange={v=>setDraft({...draft,kind:v as Kind})} disabled={!!draft.id}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{modules.filter(m=>m.id!=="files").map(m=><SelectItem key={m.id} value={m.id}>{m.name}</SelectItem>)}</SelectContent></Select></label><label>Başlık<input autoFocus required maxLength={200} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Detay<textarea rows={4} maxLength={12000} value={draft.body} onChange={e=>setDraft({...draft,body:e.target.value})}/></label>{["calendar","tasks","projects"].includes(draft.kind)&&<label>Tarih ve saat<input type="datetime-local" value={draft.date ? new Date(new Date(draft.date).getTime()-new Date(draft.date).getTimezoneOffset()*60000).toISOString().slice(0,16) : ""} required={draft.kind==="calendar"} onChange={e=>setDraft({...draft,date:e.target.value})}/></label>}{["links","projects"].includes(draft.kind)&&<label>Bağlantı<input type="url" placeholder="https://" required={draft.kind==="links"} value={draft.url} onChange={e=>setDraft({...draft,url:e.target.value})}/></label>}{draft.kind==="finance"&&<label>Tutar (₺) · gider için eksi gir<input type="number" step="0.01" required value={draft.amount} onChange={e=>setDraft({...draft,amount:Number(e.target.value)})}/></label>}{draft.kind==="tasks"&&<label className="switch-label">Yüksek öncelik<Switch checked={draft.priority==="high"} onCheckedChange={v=>setDraft({...draft,priority:v?"high":"normal"})}/></label>}<button className="primary-button" type="submit" disabled={saving}>{saving?<LoaderCircle size={17} className="spin"/>:<Check size={17}/>}Kaydet</button></form>}</DialogContent></Dialog>
 <Dialog open={settings} onOpenChange={setSettings}><DialogContent className="record-dialog"><DialogHeader><DialogTitle>Görünüm ayarları</DialogTitle><DialogDescription>Çalışma alanını kendine göre ayarla.</DialogDescription></DialogHeader><label className="switch-label">Harita animasyonu<Switch checked={motion} onCheckedChange={setMotion}/></label><p className="subtle">Renkler ve ölçüler ortak tasarım dosyasından düzenlenebilir. API anahtarı sunucuda saklanır.</p><button className="add-entry" onClick={()=>{setZoom(1);setReset(r=>r+1);setSettings(false);}}>Harita görünümünü sıfırla</button></DialogContent></Dialog>
 <AlertDialog open={!!remove} onOpenChange={o=>{if(!o)setRemove(null);}}><AlertDialogContent className="record-dialog"><AlertDialogTitle>Bu kayıt silinsin mi?</AlertDialogTitle><AlertDialogDescription>“{remove?.title}” kalıcı olarak silinecek.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Vazgeç</AlertDialogCancel><AlertDialogAction onClick={()=>{if(remove)void api("/api/entries","DELETE",{id:remove.id}).then(()=>refresh()).catch(e=>toast.error(e.message));setRemove(null);}}>Sil</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </main>;
}
