"use client";
import {useEffect,useRef} from "react";
import {modules,Kind,Entry} from "@/lib/dashhan";
type Props={entries:Entry[];focus:string;onSelect:(id:Kind|"core")=>void;zoom:number;onZoom:(zoom:number)=>void;motion:boolean;reset:number};
export default function NetworkGraph(props:Props){
 const canvas=useRef<HTMLCanvasElement>(null),live=useRef(props),zoomLevel=useRef(props.zoom),camera=useRef({x:0,y:0,angle:0}),hits=useRef<{x:number;y:number;r:number;id:Kind|"core"}[]>([]);live.current=props;zoomLevel.current=props.zoom;
 useEffect(()=>{camera.current={x:0,y:0,angle:0};},[props.reset]);
 useEffect(()=>{const el=canvas.current;if(!el)return;const ctx=el.getContext("2d");if(!ctx)return;let frame=0,w=1,h=1,time=0;const reduce=matchMedia("(prefers-reduced-motion: reduce)").matches;const resize=()=>{const r=el.getBoundingClientRect();w=r.width;h=r.height;const d=Math.min(devicePixelRatio,2);el.width=w*d;el.height=h*d;ctx.setTransform(d,0,0,d,0,0);};const obs=new ResizeObserver(resize);obs.observe(el);resize();
 const points=modules.map((m,i)=>{const a=-Math.PI/2+i*Math.PI*2/modules.length;return {...m,x:Math.cos(a)*260,y:Math.sin(a)*205,z:Math.sin(i*2)*65};});
 function draw(){if(!ctx||!el)return;const p=live.current;time+=(p.motion&&!reduce ? .011 : 0);ctx.clearRect(0,0,w,h);const scale=Math.min(w/(w<420?750:700),h/640)*p.zoom,cx=w*.51+camera.current.x,cy=h*.48+camera.current.y;
 const project=(x:number,y:number,z:number)=>{const a=camera.current.angle;const xx=x*Math.cos(a)+z*Math.sin(a),zz=z*Math.cos(a)-x*Math.sin(a);const depth=800/(800+zz);return {x:cx+xx*scale*depth,y:cy+y*scale*depth,s:scale*depth};};
 const mist=ctx.createRadialGradient(cx,cy,10,cx,cy,Math.max(w,h)*.55);mist.addColorStop(0,"#24544955");mist.addColorStop(.5,"#103c3529");mist.addColorStop(1,"#02090800");ctx.fillStyle=mist;ctx.fillRect(0,0,w,h);
 for(let i=0;i<120;i++){const px=(Math.sin(i*127.7)*.5+.5)*w,py=(Math.cos(i*89.1)*.5+.5)*h;ctx.fillStyle=`rgba(155,217,208,${.08+.08*Math.sin(time+i)})`;ctx.beginPath();ctx.arc(px,py,i%9===0?1.5:.6,0,Math.PI*2);ctx.fill();}
 const orb=(x:number,y:number,r:number,color:string,active=false)=>{const halo=ctx.createRadialGradient(x,y,0,x,y,r*3.5);halo.addColorStop(0,color+"55");halo.addColorStop(1,color+"00");ctx.fillStyle=halo;ctx.beginPath();ctx.arc(x,y,r*3.5,0,Math.PI*2);ctx.fill();const sphere=ctx.createRadialGradient(x-r*.3,y-r*.4,0,x,y,r);sphere.addColorStop(0,"#f6fff5");sphere.addColorStop(.23,color);sphere.addColorStop(.75,color+"99");sphere.addColorStop(1,"#142523");ctx.fillStyle=sphere;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();ctx.strokeStyle=color+"88";ctx.lineWidth=1;for(let j=0;j<3;j++){ctx.beginPath();ctx.arc(x,y,r+4+j*3,0,Math.PI*2);ctx.stroke();}if(active){ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,r+17,time,time+Math.PI*1.6);ctx.stroke();}};
 const hub=project(0,0,0);const nodeHits:typeof hits.current=[];
 points.forEach((n,i)=>{const pos=project(n.x+Math.sin(time*.25+i)*5,n.y,n.z),active=p.focus===n.id;ctx.strokeStyle=active?n.color+"aa":"#92c5b44d";ctx.lineWidth=active?1.5:.7;ctx.beginPath();ctx.moveTo(hub.x,hub.y);ctx.lineTo(pos.x,pos.y);ctx.stroke();const progress=((time*.14+i*.19)%1);const ax=hub.x+(pos.x-hub.x)*progress,ay=hub.y+(pos.y-hub.y)*progress;ctx.shadowColor=n.color;ctx.shadowBlur=12;ctx.fillStyle=n.color;ctx.beginPath();ctx.arc(ax,ay,active?2.5:1.3,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;
 const rows=p.entries.filter(e=>e.kind===n.id);const satellites=Math.max(3,Math.min(7,rows.length));for(let j=0;j<satellites;j++){const angle=i+j*2.4;const q=project(n.x+Math.cos(angle)*(58+j*4),n.y+Math.sin(angle)*(48+j*3),n.z+20);ctx.strokeStyle=n.color+"30";ctx.beginPath();ctx.moveTo(pos.x,pos.y);ctx.lineTo(q.x,q.y);ctx.stroke();orb(q.x,q.y,3.1*q.s,n.color);}
 orb(pos.x,pos.y,12*pos.s,n.color,active);ctx.font=`500 ${Math.max(14,15*pos.s)}px "Exo 2", sans-serif`;ctx.fillStyle=active?"#fff":"#d5e8e1";ctx.textAlign=w<700?"center":"left";const lx=w<700?pos.x:pos.x+23*pos.s,ly=w<700?pos.y+23:pos.y+3;ctx.fillText(n.name,lx,ly);ctx.font='12px "Exo 2", sans-serif';ctx.fillStyle=n.color+"b0";ctx.fillText(`${rows.length} kayıt`,lx,ly+18);nodeHits.push({x:pos.x,y:pos.y,r:30*pos.s,id:n.id});});
 orb(hub.x,hub.y,29*hub.s,"#e3c589",p.focus==="core");ctx.save();ctx.translate(hub.x,hub.y);ctx.rotate(time*.13);for(let i=0;i<72;i++){ctx.rotate(Math.PI*2/72);ctx.strokeStyle=i%3===0?"#e9d4a9aa":"#b7ddce44";ctx.beginPath();ctx.moveTo(42*hub.s,0);ctx.lineTo((i%3===0?49:46)*hub.s,0);ctx.stroke();}ctx.restore();ctx.font='600 14px "Exo 2", sans-serif';ctx.textAlign="center";ctx.fillStyle="#f1e1bf";ctx.fillText("DASHHAN",hub.x,hub.y+71*hub.s);ctx.font='11px "Exo 2", sans-serif';ctx.fillStyle="#80b4a5";ctx.fillText("PERSONAL AI CORE",hub.x,hub.y+91*hub.s);nodeHits.push({x:hub.x,y:hub.y,r:51*hub.s,id:"core"});hits.current=nodeHits;frame=requestAnimationFrame(draw);}
 draw();let down:{x:number;y:number;ox:number;oy:number;angle:number;button:number}|null=null;let moved=false;
 const start=(e:PointerEvent)=>{if(e.button!==0&&e.button!==1)return;if(e.button===1)e.preventDefault();down={x:e.clientX,y:e.clientY,ox:camera.current.x,oy:camera.current.y,angle:camera.current.angle,button:e.button};moved=false;el.setPointerCapture(e.pointerId);};
 const move=(e:PointerEvent)=>{if(down){const dx=e.clientX-down.x,dy=e.clientY-down.y;moved ||= Math.hypot(dx,dy)>5;if(e.shiftKey)camera.current.angle=down.angle+dx*.006;else{camera.current.x=down.ox+dx;camera.current.y=down.oy+dy;}}else{const r=el.getBoundingClientRect();el.style.cursor=hits.current.some(n=>Math.hypot(n.x-e.clientX+r.left,n.y-e.clientY+r.top)<n.r)?"pointer":"grab";}};
 const end=(e:PointerEvent)=>{if(e.type!=="pointercancel"&&!moved&&down?.button===0){const r=el.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;const n=hits.current.find(n=>Math.hypot(n.x-x,n.y-y)<n.r);if(n)live.current.onSelect(n.id);}down=null;};
 const wheel=(e:WheelEvent)=>{e.preventDefault();if(!e.deltaY)return;const delta=Math.max(-200,Math.min(200,e.deltaY*(e.deltaMode===1?16:e.deltaMode===2?h:1)));const previous=zoomLevel.current,next=Math.min(1.8,Math.max(.55,previous*Math.exp(-delta*.0015)));if(next===previous)return;const r=el.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,ratio=next/previous;camera.current.x=x-w*.51-(x-w*.51-camera.current.x)*ratio;camera.current.y=y-h*.48-(y-h*.48-camera.current.y)*ratio;zoomLevel.current=next;live.current.onZoom(next);if(down)down={...down,x:e.clientX,y:e.clientY,ox:camera.current.x,oy:camera.current.y};};
 const preventMiddleScroll=(e:MouseEvent)=>{if(e.button===1)e.preventDefault();};
 el.addEventListener("pointerdown",start);el.addEventListener("pointermove",move);el.addEventListener("pointerup",end);el.addEventListener("pointercancel",end);el.addEventListener("wheel",wheel,{passive:false});el.addEventListener("mousedown",preventMiddleScroll);el.addEventListener("auxclick",preventMiddleScroll);
 return()=>{cancelAnimationFrame(frame);obs.disconnect();el.removeEventListener("pointerdown",start);el.removeEventListener("pointermove",move);el.removeEventListener("pointerup",end);el.removeEventListener("pointercancel",end);el.removeEventListener("wheel",wheel);el.removeEventListener("mousedown",preventMiddleScroll);el.removeEventListener("auxclick",preventMiddleScroll);};
 },[]);
 return <canvas ref={canvas} className="network-canvas" aria-label="Kişisel bağlantı haritan. Bölümleri klavyeyle açmak için sol menüyü kullan."/>;
}
